
apiVersion: v1
kind: Pod
metadata:
    name: eb-ms-pod
    labels:
      env: uat-env
      app: eb-ms-app
    namespace: uat
spec:
  containers:
    - name: eb-ms-nginx-instance
      image: nginx
      ports:
        - name: http
          containerPort: 80
