apiVersion: v1
kind: Service
metadata:
  name: eb-ms-pod-service
  labels:
    env: uat-env
    app: eb-ms-app 
  namespace: uat #<ns-name>
spec:
  type: NodePort
  selector:
    app: eb-ms-app #[app: eb-ms-app]
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
       